# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(verbose_name='date')),
                ('Category', models.CharField(max_length=100)),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
