# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Amount',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Category',
            field=models.CharField(choices=[('Home', 'Home'), ('Grooceries', 'Grooceries')], default='Home', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2018, 5, 16, 16, 17, 2, 120288)),
        ),
    ]
