# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 16:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bill', '0002_auto_20180516_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2018, 5, 16, 16, 17, 59, 629376)),
        ),
    ]
