# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0015_auto_20180517_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Customer',
            field=models.CharField(default='J', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2018, 5, 17, 10, 26, 47, 875230)),
        ),
    ]
