# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0030_auto_20180517_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='user',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='bill',
            name='Category',
            field=models.CharField(choices=[('Home', 'Home'), ('Groceries', 'Groceries')], default='Home', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2018, 5, 17, 18, 49, 28, 407045)),
        ),
    ]
