# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0031_auto_20180517_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2018, 5, 17, 18, 57, 32, 216041)),
        ),
    ]
