# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0033_auto_20180517_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Category',
            field=models.CharField(choices=[('Home', 'Home'), ('Finances', 'Finances'), ('Daily expenses', 'Daily expenses'), ('Health', 'Health'), ('Holidays', 'Holidays'), ('Investments', 'Investments'), ('Other', 'Other')], default='Home', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2018, 5, 17, 19, 6, 24, 882856)),
        ),
    ]
